name: jaguar_orm_cli
description: CLI and generator for jaguar_orm
version: 0.2.1-dev
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_orm

executables:
  orm:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  jaguar_query: ^0.2.8
  jaguar_orm: ^0.2.0-dev
  source_gen: ^0.7.0
  build_runner: '>=0.3.4 <0.4.0'
  build: '>=0.9.3 <0.10.0'
  yaml: ">=2.1.10 <3.0.0"
  intl: ">=0.14.0 <0.15.0"

dev_dependencies:
  test: ^0.12.0
